# Analyze the SNP calls for each species.
# Process the SNP calls, plot the SFS,
# and calculate the number of fixed differences between pairs of samples.
rule calculateFixedDifferences:
    input:
        snpsDepth="workflow/out/midasOutput/snps/HouseholdTransmission-Stool/{species}/snps_depth.txt.gz",
        snpsFreq="workflow/out/midasOutput/snps/HouseholdTransmission-Stool/{species}/snps_freq.txt.gz",
        snpsInfo="workflow/out/midasOutput/snps/HouseholdTransmission-Stool/{species}/snps_info.txt.gz",
        
    output:
        "workflow/report/calculateFixedDifferences/{species}/done.txt"
    params:
        plotDefaults=config["plotDefaults"],
        indir="workflow/out/midasOutput/snps/HouseholdTransmission-Stool/",
        outdir="workflow/report/calculateFixedDifferences/",
        species="{species}"
    conda:
        "../../workflow/envs/Renv-minimal.yml"
    script:
        "../scripts/calculateFixedDifferences.R"

# Compress the file of fixed differences.
rule compressFixedDifferences:
	input:
		fixedDiffs="{dir}/fixedDiffs_filterCoverage.txt"
	output:
		fixedDiffs="{dir}/fixedDiffs_filterCoverage.txt.gz"
	shell:
		"""
		gzip {input.fixedDiffs}
		"""
	
# Analyze the SNP calls for each species.
# Process the SNP calls, import the public HMP SNPs where available,
# and perform strain "fishing" to detect strains shared between subjects.
rule performStrainFishing:
    input:
        snpsDepth="workflow/out/midasOutput/snps/HouseholdTransmission-Stool/{species}/snps_depth.txt.gz",
        snpsFreq="workflow/out/midasOutput/snps/HouseholdTransmission-Stool/{species}/snps_freq.txt.gz",
        snpsInfo="workflow/out/midasOutput/snps/HouseholdTransmission-Stool/{species}/snps_info.txt.gz",
        
    output:
        "workflow/report/performStrainFishing/{species}/done.txt"
    params:
        plotDefaults=config["plotDefaults"],
        indir="workflow/out/midasOutput/snps/HouseholdTransmission-Stool/",
        outdir="workflow/report/performStrainFishing/",
        species="{species}",
        HMPsnpsdir="workflow/out/midasOutput/HMP/snp_prevalences/"
    conda:
        "../../workflow/envs/Renv-minimal.yml"
    script:
        "../scripts/performStrainFishing.R"
		
# Remove empty files generated by strain fishing.
rule removeEmptyStrainFishing:
	output:
		"workflow/report/performStrainFishing/removeEmptyStrainFishing.done"
	shell:
		"""
		workflow/scripts/removeEmptyStrainFishing.sh
		"""